baseline_set_size: 10000
batch_size: 512
ff_dim: 512
gradient_clip_val: 1
hidden_dim: 128
input_dim: 2
k_dim: 16
lr: 0.0001
max_epochs: 100
n_batch_per_epoch: 2500
n_head: 8
n_layer: 3
n_node: 20
num_workers: 4
v_dim: 16
val_set: null
